### ISSUE TITLE
☂️ Umbrella Issue - Feature Ideas

### ISSUE THREAD

**Issue by PeteTheHeat** [637labs/crypto-dollar-cost-averaging#25]
Just going to use this as a note pad for feature ideas.

MVP

- [ ] Navigation refactor
- [ ] API Key creation/deletion walkthrough
- [ ] Monetization
- [ ] Terms of Service/safety tips/something to cover our ass
- [ ] Validate "transfer" credential not given
- [ ] Mobile layout polish

Non-MVP

- [ ] User sessions? (If I open another tab of Nckl with it open, it's jank)
- [ ] Lifetime savings calculator (store a running total of how much you've saved)
- [ ] Delete account flow (this might need to be MVP?)
- [ ] Affiliate links 
- [ ] FTX support 
- [x] Optimizing daily schedule for buys
- [ ] Coinbase Advanced Trade support
